exports.getCountry = (provider, country) => {
  let data;

  let list;

  switch (provider) {
    case "fivesim":
      list = {
        Albania: "albania",
        Angola: "angola",
        Aruba: "aruba",
        Australia: "australia",
        Azerbaijan: "azerbaijan",
        Benin: "benin",
        Bolivia: "bolivia",
        Botswana: "botswana",
        Brazil: "brazil",
        Cambodia: "cambodia",
        Canada: "canada",
        "Cape Verde": "capeverde",
        Chile: "chile",
        China: "china",
        Colombia: "colombia",
        Czechia: "czech",
        Egypt: "egypt",
        "Equatorial Guinea": "equatorialguinea",
        Gabon: "gabon",
        Gambia: "gambia",
        Guadeloupe: "guadeloupe",
        "Guinea:Bissau": "guineabissau",
        Haiti: "haiti",
        "Hong Kong": "hongkong",
        Hungary: "hungary",
        India: "india",
        Iran: "iran",
        Italy: "italy",
        Kazakhstan: "kazakhstan",
        Kenya: "kenya",
        Kuwait: "kuwait",
        Kyrgyzstan: "kyrgyzstan",
        Laos: "laos",
        Libya: "libya",
        Lithuania: "lithuania",
        Luxembourg: "luxembourg",
        Macau: "macau",
        Malawi: "malawi",
        Malaysia: "malaysia",
        Maldives: "maldives",
        Mauritius: "mauritius",
        Mongolia: "mongolia",
        Montenegro: "montenegro",
        Montserrat: "montserrat",
        Myanmar: "myanmar",
        Nepal: "nepal",
        Netherlands: "netherlands",
        Nicaragua: "nicaragua",
        Niger: "niger",
        Panama: "panama",
        Afghanistan: "afghanistan",
        Algeria: "algeria",
        Anguilla: "anguilla",
        "Antigua and Barbuda": "antiguaandbarbuda",
        Argentina: "argentina",
        Armenia: "armenia",
        Austria: "austria",
        Bahamas: "bahamas",
        Bahrain: "bahrain",
        Bangladesh: "bangladesh",
        Barbados: "barbados",
        Belarus: "belarus",
        Belgium: "belgium",
        Belize: "belize",
        Bhutan: "bhutane",
        "Bosnia and Herzegovina": "bih",
        "British Virgin Islands": "virginislands",
        Bulgaria: "bulgaria",
        "Burkina Faso": "burkinafaso",
        Burundi: "burundi",
        Cameroon: "cameroon",
        "Cayman Islands": "caymanislands",
        Chad: "chad",
        Comoros: "comoros",
        Congo: "congo",
        "Costa Rica": "costarica",
        Croatia: "croatia",
        Cuba: "cuba",
        Cyprus: "cyprus",
        Djibouti: "djibouti",
        Dominica: "dominica",
        "Dominican Republic": "dominicana",
        "DR Congo": "drcongo",
        "East Timor": "easttimor",
        Ecuador: "ecuador",
        England: "england",
        Eritrea: "eritrea",
        Estonia: "estonia",
        Ethiopia: "ethiopia",
        Finland: "finland",
        France: "france",
        "French Guiana": "frenchguiana",
        Georgia: "georgia",
        Germany: "germany",
        Ghana: "ghana",
        Greece: "greece",
        Grenada: "grenada",
        Guatemala: "guatemala",
        Guinea: "guinea",
        Guyana: "guyana",
        Honduras: "honduras",
        Indonesia: "indonesia",
        Iraq: "iraq",
        Ireland: "ireland",
        Israel: "israel",
        "Ivory Coast": "ivorycoast",
        Jamaica: "jamaica",
        Japan: "japan",
        Jordan: "jordan",
        Latvia: "latvia",
        Lesotho: "lesotho",
        Liberia: "liberia",
        Madagascar: "madagascar",
        Mali: "mali",
        Mauritania: "mauritania",
        Mexico: "mexico",
        Moldova: "moldova",
        Morocco: "morocco",
        Mozambique: "mozambique",
        Namibia: "namibia",
        "New Caledonia": "newcaledonia",
        "New Zealand": "newzealand",
        Nigeria: "nigeria",
        "North Macedonia": "northmacedonia",
        Norway: "norway",
        Oman: "oman",
        Pakistan: "pakistan",
        "Papua New Guinea": "papuanewguinea",
        Paraguay: "paraguay",
        Peru: "peru",
        Philippines: "philippines",
        Poland: "poland",
        Portugal: "portugal",
        Puertorico: "puertorico",
        Qatar: "qatar",
        "Republic of Seychelles": "seychelles",
        Reunion: "reunion",
        Romania: "romania",
        Russia: "russia",
        Rwanda: "rwanda",
        "Saint Kitts and Nevis": "saintkittsandnevis",
        "Saint Lucia": "saintlucia",
        "Saint Vincent and the Grenadines": "saintvincentandgrenadines",
        Salvador: "salvador",
        Samoa: "samoa",
        "Sao Tome and Principe": "saotomeandprincipe",
        "Saudi Arabia": "saudiarabia",
        Senegal: "senegal",
        Serbia: "serbia",
        "Sierra Leone": "sierraleone",
        Singapore: "singapore",
        Slovakia: "slovakia",
        Slovenia: "slovenia",
        "Solomon Islands": "solomonislands",
        Somalia: "somalia",
        "South Africa": "southafrica",
        "South Sudan": "southsudan",
        Spain: "spain",
        "Sri Lanka": "srilanka",
        Sudan: "sudan",
        Suriname: "suriname",
        Swaziland: "swaziland",
        Sweden: "sweden",
        Switzerland: "switzerland",
        Syria: "syria",
        Taiwan: "taiwan",
        Tajikistan: "tajikistan",
        Tanzania: "tanzania",
        Thailand: "thailand",
        Togo: "togo",
        Tonga: "tonga",
        "Trinidad and Tobago": "tit",
        Tunisia: "tunisia",
        Turkey: "turkey",
        Turkmenistan: "turkmenistan",
        "Turks and Caicos Island": "turksandcaicos",
        UAE: "uae",
        Uganda: "uganda",
        Ukraine: "ukraine",
        Uruguay: "uruguay",
        "United States": "usa",
        Uzbekistan: "uzbekistan",
        Venezuela: "venezuela",
        Vietnam: "vietnam",
        Yemen: "yemen",
        Zambia: "zambia",
        Zimbabwe: "zimbabwe",
      };

      if (country in list) {
        data = list[country];
      } else {
        data = null;
      }
      break;
    case "onlinesim":
      list = {
        Russia: "7",
        Ukraine: "380",
        Germany: "49",
        Britain: "44",
        France: "33",
        Spain: "34",
        Sweden: "46",
        Netherlands: "31",
        Denmark: "45",
        Cyprus: "357",
        Canada: "1000",
        "United States": "1",
        Poland: "48",
        Romania: "40",
        Indonesia: "62",
        Philippines: "63",
        Latvia: "371",
        Lithuania: "370",
        Estonia: "372",
        Moldova: "373",
        Georgia: "995",
        Kyrgyzstan: "996",
        Kazakhstan: "77",
        Brazil: "55",
        Haiti: "509",
        Ghana: "233",
        Turkey: "90",
        Egypt: "20",
        India: "91",
        Mexico: "52",
        Argentina: "54",
        Yemen: "967",
        Nigeria: "234",
        "Ivory Coast": "225",
        Colombia: "57",
        Honduras: "504",
        Pakistan: "92",
        "Burkina Faso": "226",
        Nepal: "977",
        Iraq: "964",
        Azerbaijan: "994",
        Iran: "98",
        Vietnam: "84",
        Bolivia: "591",
        "Sri Lanka": "94",
        Mongolia: "976",
      };

      if (country in list) {
        data = list[country];
      } else {
        data = null;
      }
      break;
    case "smsactivate":
      list = {
        Russia: "0",
        Ukraine: "1",
        Kazakhstan: "2",
        China: "3",
        Philippines: "4",
        Myanmar: "5",
        Indonesia: "6",
        Malaysia: "7",
        Kenya: "8",
        Tanzania: "9",
        Vietnam: "10",
        Kyrgyzstan: "11",
        "United States": "187",
        "United States (virtual)": "12",
        Israel: "13",
        HongKong: "14",
        Poland: "15",
        England: "16",
        DCongo: "18",
        Nigeria: "19",
        Macao: "20",
        Egypt: "21",
        India: "22",
        Ireland: "23",
        Cambodia: "24",
        Laos: "25",
        Haiti: "26",
        Ivory: "27",
        Gambia: "28",
        Serbia: "29",
        Yemen: "30",
        Southafrica: "31",
        Romania: "32",
        Colombia: "33",
        Estonia: "34",
        Canada: "36",
        Morocco: "37",
        Ghana: "38",
        Argentina: "39",
        Uzbekistan: "40",
        Cameroon: "41",
        Chad: "42",
        Germany: "43",
        Lithuania: "44",
        Croatia: "45",
        Sweden: "46",
        Iraq: "47",
        Netherlands: "48",
        Latvia: "49",
        Austria: "50",
        Belarus: "51",
        Thailand: "52",
        Saudiarabia: "53",
        Mexico: "54",
        Taiwan: "55",
        Spain: "56",
        Iran: "57",
        Algeria: "58",
        Slovenia: "59",
        Bangladesh: "60",
        Senegal: "61",
        Turkey: "62",
        Czech: "63",
        Srilanka: "64",
        Peru: "65",
        Pakistan: "66",
        Newzealand: "67",
        Guinea: "68",
        Mali: "69",
        Venezuela: "70",
        Ethiopia: "71",
        Mongolia: "72",
        Brazil: "73",
        Afghanistan: "74",
        Uganda: "75",
        Angola: "76",
        Cyprus: "77",
        France: "78",
        Papua: "79",
        Mozambique: "80",
        Nepal: "81",
        Belgium: "82",
        Bulgaria: "83",
        Hungary: "84",
        Moldova: "85",
        Italy: "86",
        Paraguay: "87",
        Honduras: "88",
        Tunisia: "89",
        Nicaragua: "90",
        Timorleste: "91",
        Bolivia: "92",
        Costarica: "93",
        Guatemala: "94",
        Uae: "95",
        Zimbabwe: "96",
        Puertorico: "97",
        Sudan: "98",
        Togo: "99",
        Kuwait: "100",
        Salvador: "101",
        Libyan: "102",
        Jamaica: "103",
        Trinidad: "104",
        Ecuador: "105",
        Swaziland: "106",
        Oman: "107",
        Bosnia: "108",
        Dominican: "109",
        Syrian: "110",
        Qatar: "111",
        Panama: "112",
        Cuba: "113",
        Mauritania: "114",
        Sierraleone: "115",
        Jordan: "116",
        Portugal: "117",
        Barbados: "118",
        Burundi: "119",
        Benin: "120",
        Brunei: "121",
        Bahamas: "122",
        Botswana: "123",
        Belize: "124",
        Caf: "125",
        Dominica: "126",
        Grenada: "127",
        Georgia: "128",
        Greece: "129",
        Guineabissau: "130",
        Guyana: "131",
        Iceland: "132",
        Comoros: "133",
        Saintkitts: "134",
        Liberia: "135",
        Lesotho: "136",
        Malawi: "137",
        Namibia: "138",
        Niger: "139",
        Rwanda: "140",
        Slovakia: "141",
        Suriname: "142",
        Tajikistan: "143",
        Monaco: "144",
        Bahrain: "145",
        Reunion: "146",
        Zambia: "147",
        Armenia: "148",
        Somalia: "149",
        Congo: "150",
        Chile: "151",
        Furkinafaso: "152",
        Lebanon: "153",
        Gabon: "154",
        Albania: "155",
        Uruguay: "156",
        Mauritius: "157",
        Bhutan: "158",
        Maldives: "159",
        Guadeloupe: "160",
        Turkmenistan: "161",
        Frenchguiana: "162",
        Finland: "163",
        Saintlucia: "164",
        Luxembourg: "165",
        Saintvincentgrenadines: "166",
        Equatorialguinea: "167",
        Djibouti: "168",
        Antiguabarbuda: "169",
        Caymanislands: "170",
        Montenegro: "171",
        Switzerland: "173",
        Norway: "174",
        Australia: "175",
        Eritrea: "176",
        Southsudan: "177",
        Saotomeandprincipe: "178",
        Aruba: "179",
        Montserrat: "180",
        Anguilla: "181",
        Northmacedonia: "183",
        Seychelles: "184",
        Newcaledonia: "185",
        Capeverde: "186",
        Southkorea: "190",
      };

      if (country in list) {
        data = list[country];
      } else {
        data = null;
      }
      break;
    case "smspva":
      list = {
        Ukraine: "UA",
        Germany: "DE",
        Italy: "IT",
        Kazakhstan: "KZ",
        Haiti: "HT",
        Romania: "RO",
        Argentina: "AR",
        "Bos. and Herz.": "BA",
        Brazil: "BR",
        Cambodia: "KH",
        "Cameroon (Virtual)": "CM",
        Canada: "CA_V",
        Chile: "CL",
        Cyprus: "CY",
        Dominicana: "DO",
        "Egypt (Virtual)": "EG",
        Estonia: "EE",
        Finland: "FI",
        France: "FR",
        "Ghana (Virtual)": "GH",
        "India (Virtual)": "IN",
        Indonesia: "ID",
        "Iraq (Virtual)": "IQ",
        Ireland: "IE",
        Kenya: "KE",
        Kyrgyzstan: "KG",
        Laos: "LA",
        Latvia: "LV",
        Lithuania: "LT",
        Malaysia: "MY",
        Mexico: "MX",
        Moldova: "MD",
        Morocco: "MA",
        Netherlands: "NL",
        "New Zealand": "NZ",
        Nigeria: "NG",
        "Pakistan (Virtual)": "PK",
        Philippines: "PH",
        Poland: "PL",
        Portugal: "PT",
        "South Africa": "ZA",
        Spain: "ES",
        Sweden: "SE",
        "United Kingdom": "UK",
        "United States": "US",
        Vietnam: "VN",
      };

      if (country in list) {
        data = list[country];
      } else {
        data = null;
      }

      break;
  }

  return data;
};

exports.getService = (provider, service) => {
  let data;
  let list;

  switch (provider) {
    case "fivesim":
      list = {
        amazon: "amazon",
        nike: "nike",
        google: "google",
        yahoo: "yahoo",
        target: "other",
        outlook: "microsoft",
      };

      if (service in list) {
        data = list[service];
      } else {
        data = null;
      }
      break;
    case "onlinesim":
      list = {
        amazon: "Other",
        nike: "Nike",
        google: "Google",
        yahoo: "Yahoo",
        target: "Other",
        outlook: "Microsoft",
      };

      if (service in list) {
        data = list[service];
      } else {
        data = null;
      }
      break;
    case "smsactivate":
      list = {
        amazon: "am",
        nike: "ew",
        google: "go",
        yahoo: "mb",
        target: "ot",
        outlook: "mm",
      };

      if (service in list) {
        data = list[service];
      } else {
        data = null;
      }
      break;
  }

  return data;
};
